// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action addnew;
    
    private Gtk.Action properties;
    
    private Gtk.Action delete;
    
    private Gtk.Action refresh;
    
    private Gtk.Action preferences;
    
    private Gtk.Action About;
    
    private Gtk.Action about;
    
    private Gtk.Action connect;
    
    private Gtk.Action disconnect;
    
    private Gtk.Action quit;
    
    private Gtk.Action File;
    
    private Gtk.Action Edit;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.HPaned mainpaned;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.Expander expander1;
    
    private Gtk.Alignment alignment1;
    
    private Gtk.VBox vbox6;
    
    private Gtk.Button generalinfobutton;
    
    private Gtk.Label GtkLabel17;
    
    private Gtk.Expander expander2;
    
    private Gtk.Alignment alignment2;
    
    private Gtk.VBox vbox3;
    
    private Gtk.Button taxesbutton;
    
    private Gtk.Button categoriesbutton;
    
    private Gtk.Button productsbutton;
    
    private Gtk.Label GtkLabel16;
    
    private Gtk.Expander expander3;
    
    private Gtk.Alignment alignment3;
    
    private Gtk.VBox vbox5;
    
    private Gtk.Label GtkLabel20;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Edition");
        this.addnew = new Gtk.Action("addnew", Mono.Unix.Catalog.GetString("A_jouter"), null, "gtk-add");
        this.addnew.ShortLabel = Mono.Unix.Catalog.GetString("A_jouter");
        w2.Add(this.addnew, null);
        this.properties = new Gtk.Action("properties", Mono.Unix.Catalog.GetString("_Propriétés"), null, "gtk-properties");
        this.properties.ShortLabel = Mono.Unix.Catalog.GetString("_Propriétés");
        w2.Add(this.properties, null);
        this.delete = new Gtk.Action("delete", Mono.Unix.Catalog.GetString("_Supprimer"), null, "gtk-delete");
        this.delete.ShortLabel = Mono.Unix.Catalog.GetString("_Supprimer");
        w2.Add(this.delete, null);
        this.refresh = new Gtk.Action("refresh", Mono.Unix.Catalog.GetString("A_ctualiser"), null, "gtk-refresh");
        this.refresh.ShortLabel = Mono.Unix.Catalog.GetString("A_ctualiser");
        w2.Add(this.refresh, null);
        this.preferences = new Gtk.Action("preferences", Mono.Unix.Catalog.GetString("_Préférences"), null, "gtk-preferences");
        this.preferences.ShortLabel = Mono.Unix.Catalog.GetString("_Préférences");
        w2.Add(this.preferences, null);
        this.About = new Gtk.Action("About", Mono.Unix.Catalog.GetString("_Help"), null, null);
        this.About.ShortLabel = Mono.Unix.Catalog.GetString("_Help");
        w2.Add(this.About, null);
        this.about = new Gtk.Action("about", Mono.Unix.Catalog.GetString("À _propos"), null, "gtk-about");
        this.about.ShortLabel = Mono.Unix.Catalog.GetString("À _propos");
        w2.Add(this.about, null);
        w1.InsertActionGroup(w2, 0);
        Gtk.ActionGroup w3 = new Gtk.ActionGroup("General");
        this.connect = new Gtk.Action("connect", Mono.Unix.Catalog.GetString("_Connecter"), null, "gtk-connect");
        this.connect.ShortLabel = Mono.Unix.Catalog.GetString("_Connecter");
        w3.Add(this.connect, null);
        this.disconnect = new Gtk.Action("disconnect", Mono.Unix.Catalog.GetString("_Déconnecter"), null, "gtk-disconnect");
        this.disconnect.ShortLabel = Mono.Unix.Catalog.GetString("_Déconnecter");
        w3.Add(this.disconnect, null);
        this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quitter"), null, "gtk-quit");
        this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quitter");
        w3.Add(this.quit, null);
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("_File");
        w3.Add(this.File, null);
        this.Edit = new Gtk.Action("Edit", Mono.Unix.Catalog.GetString("_Edit"), null, null);
        this.Edit.ShortLabel = Mono.Unix.Catalog.GetString("_Edit");
        w3.Add(this.Edit, null);
        w1.InsertActionGroup(w3, 1);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='disconnect'/><menuitem action='connect'/><separator/><menuitem action='quit'/></menu><menu action='Edit'><menuitem action='addnew'/><menuitem action='properties'/><menuitem action='refresh'/><menuitem action='delete'/><separator/><menuitem action='preferences'/></menu><menu action='About'><menuitem action='about'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='connect'/><toolitem action='disconnect'/><separator/><toolitem action='addnew'/><toolitem action='properties'/><toolitem action='delete'/><toolitem action='refresh'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.vbox1.Add(this.toolbar1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
        w5.Position = 1;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.mainpaned = new Gtk.HPaned();
        this.mainpaned.CanFocus = true;
        this.mainpaned.Name = "mainpaned";
        this.mainpaned.Position = 220;
        // Container child mainpaned.Gtk.Paned+PanedChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.WidthRequest = 190;
        this.scrolledwindow1.CanFocus = true;
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        Gtk.Viewport w6 = new Gtk.Viewport();
        w6.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        this.vbox2.BorderWidth = ((uint)(6));
        // Container child vbox2.Gtk.Box+BoxChild
        this.expander1 = new Gtk.Expander(null);
        this.expander1.CanFocus = true;
        this.expander1.Name = "expander1";
        this.expander1.Expanded = true;
        // Container child expander1.Gtk.Container+ContainerChild
        this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment1.Name = "alignment1";
        this.alignment1.LeftPadding = ((uint)(15));
        // Container child alignment1.Gtk.Container+ContainerChild
        this.vbox6 = new Gtk.VBox();
        this.vbox6.Name = "vbox6";
        this.vbox6.Spacing = 6;
        // Container child vbox6.Gtk.Box+BoxChild
        this.generalinfobutton = new Gtk.Button();
        this.generalinfobutton.CanFocus = true;
        this.generalinfobutton.Name = "generalinfobutton";
        this.generalinfobutton.UseUnderline = true;
        this.generalinfobutton.Label = Mono.Unix.Catalog.GetString("Informations");
        this.vbox6.Add(this.generalinfobutton);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox6[this.generalinfobutton]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        this.alignment1.Add(this.vbox6);
        this.expander1.Add(this.alignment1);
        this.GtkLabel17 = new Gtk.Label();
        this.GtkLabel17.Name = "GtkLabel17";
        this.GtkLabel17.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
        this.GtkLabel17.UseMarkup = true;
        this.GtkLabel17.UseUnderline = true;
        this.expander1.LabelWidget = this.GtkLabel17;
        this.vbox2.Add(this.expander1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.expander1]));
        w10.Position = 0;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.expander2 = new Gtk.Expander(null);
        this.expander2.CanFocus = true;
        this.expander2.Name = "expander2";
        this.expander2.Expanded = true;
        // Container child expander2.Gtk.Container+ContainerChild
        this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment2.Name = "alignment2";
        this.alignment2.LeftPadding = ((uint)(15));
        // Container child alignment2.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.taxesbutton = new Gtk.Button();
        this.taxesbutton.CanFocus = true;
        this.taxesbutton.Name = "taxesbutton";
        this.taxesbutton.UseUnderline = true;
        this.taxesbutton.Label = Mono.Unix.Catalog.GetString("Taxes");
        this.vbox3.Add(this.taxesbutton);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox3[this.taxesbutton]));
        w11.Position = 0;
        w11.Expand = false;
        w11.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.categoriesbutton = new Gtk.Button();
        this.categoriesbutton.CanFocus = true;
        this.categoriesbutton.Name = "categoriesbutton";
        this.categoriesbutton.UseUnderline = true;
        this.categoriesbutton.Label = Mono.Unix.Catalog.GetString("Categories");
        this.vbox3.Add(this.categoriesbutton);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox3[this.categoriesbutton]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.productsbutton = new Gtk.Button();
        this.productsbutton.CanFocus = true;
        this.productsbutton.Name = "productsbutton";
        this.productsbutton.UseUnderline = true;
        this.productsbutton.Label = Mono.Unix.Catalog.GetString("Products");
        this.vbox3.Add(this.productsbutton);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox3[this.productsbutton]));
        w13.Position = 2;
        w13.Expand = false;
        w13.Fill = false;
        this.alignment2.Add(this.vbox3);
        this.expander2.Add(this.alignment2);
        this.GtkLabel16 = new Gtk.Label();
        this.GtkLabel16.Name = "GtkLabel16";
        this.GtkLabel16.LabelProp = Mono.Unix.Catalog.GetString("<b>Products and prices</b>");
        this.GtkLabel16.UseMarkup = true;
        this.GtkLabel16.UseUnderline = true;
        this.expander2.LabelWidget = this.GtkLabel16;
        this.vbox2.Add(this.expander2);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.expander2]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.expander3 = new Gtk.Expander(null);
        this.expander3.CanFocus = true;
        this.expander3.Name = "expander3";
        // Container child expander3.Gtk.Container+ContainerChild
        this.alignment3 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment3.Name = "alignment3";
        this.alignment3.LeftPadding = ((uint)(15));
        // Container child alignment3.Gtk.Container+ContainerChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        this.alignment3.Add(this.vbox5);
        this.expander3.Add(this.alignment3);
        this.GtkLabel20 = new Gtk.Label();
        this.GtkLabel20.Name = "GtkLabel20";
        this.GtkLabel20.LabelProp = Mono.Unix.Catalog.GetString("<b>Sales and reports</b>");
        this.GtkLabel20.UseMarkup = true;
        this.GtkLabel20.UseUnderline = true;
        this.expander3.LabelWidget = this.GtkLabel20;
        this.vbox2.Add(this.expander3);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.expander3]));
        w19.Position = 2;
        w6.Add(this.vbox2);
        this.scrolledwindow1.Add(w6);
        this.mainpaned.Add(this.scrolledwindow1);
        Gtk.Paned.PanedChild w22 = ((Gtk.Paned.PanedChild)(this.mainpaned[this.scrolledwindow1]));
        w22.Resize = false;
        w22.Shrink = false;
        this.vbox1.Add(this.mainpaned);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.mainpaned]));
        w23.Position = 2;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w24.Position = 3;
        w24.Expand = false;
        w24.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 638;
        this.DefaultHeight = 600;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.addnew.Activated += new System.EventHandler(this.OnAdd);
        this.properties.Activated += new System.EventHandler(this.OnProperties);
        this.delete.Activated += new System.EventHandler(this.OnDelete);
        this.refresh.Activated += new System.EventHandler(this.OnRefresh);
        this.preferences.Activated += new System.EventHandler(this.OnPreferences);
        this.connect.Activated += new System.EventHandler(this.OnConnect);
        this.disconnect.Activated += new System.EventHandler(this.OnDisconnect);
        this.quit.Activated += new System.EventHandler(this.OnExit);
        this.generalinfobutton.Clicked += new System.EventHandler(this.OnGeneralInfoClicked);
        this.taxesbutton.Clicked += new System.EventHandler(this.OnTaxesClicked);
        this.categoriesbutton.Clicked += new System.EventHandler(this.OnCategoriesClicked);
        this.productsbutton.Clicked += new System.EventHandler(this.OnProductsClicked);
    }
}
