// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace suposadmin {
    
    
    public partial class CategoriesViewWidget {
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView categoriestreeview;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget suposadmin.CategoriesViewWidget
            Stetic.BinContainer w1 = Stetic.BinContainer.Attach(this);
            Gtk.UIManager w2 = new Gtk.UIManager();
            Gtk.ActionGroup w3 = new Gtk.ActionGroup("Default");
            w2.InsertActionGroup(w3, 0);
            this.Name = "suposadmin.CategoriesViewWidget";
            // Container child suposadmin.CategoriesViewWidget.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w4 = new Gtk.Viewport();
            w4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.categoriestreeview = new Gtk.TreeView();
            this.categoriestreeview.CanFocus = true;
            this.categoriestreeview.Name = "categoriestreeview";
            this.categoriestreeview.HeadersClickable = true;
            w4.Add(this.categoriestreeview);
            this.scrolledwindow1.Add(w4);
            this.Add(this.scrolledwindow1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            w1.SetUiManager(w2);
            this.Show();
        }
    }
}
