// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace suposadmin {
    
    
    public partial class TaxesViewWidget {
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView taxestreeview;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget suposadmin.TaxesViewWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "suposadmin.TaxesViewWidget";
            // Container child suposadmin.TaxesViewWidget.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.taxestreeview = new Gtk.TreeView();
            this.taxestreeview.CanFocus = true;
            this.taxestreeview.Name = "taxestreeview";
            this.taxestreeview.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.taxestreeview);
            this.Add(this.GtkScrolledWindow);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
