// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace suposadmin {
    
    
    public partial class ProductDialog {
        
        private Gtk.Table table1;
        
        private Gtk.ComboBox categorycombobox;
        
        private Gtk.Button iconbutton;
        
        private Gtk.Entry identry;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Entry nameentry;
        
        private Gtk.SpinButton pricespinbutton;
        
        private Gtk.SpinButton pricetispinbutton;
        
        private Gtk.ComboBox taxcombobox;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget suposadmin.ProductDialog
            this.Name = "suposadmin.ProductDialog";
            this.Title = Mono.Unix.Catalog.GetString("Product");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child suposadmin.ProductDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(7)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.categorycombobox = new Gtk.ComboBox();
            this.categorycombobox.Name = "categorycombobox";
            this.table1.Add(this.categorycombobox);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.categorycombobox]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(3));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.iconbutton = new Gtk.Button();
            this.iconbutton.WidthRequest = 60;
            this.iconbutton.HeightRequest = 60;
            this.iconbutton.CanFocus = true;
            this.iconbutton.Name = "iconbutton";
            this.iconbutton.Xalign = 0F;
            this.iconbutton.Label = null;
            this.table1.Add(this.iconbutton);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.iconbutton]));
            w3.TopAttach = ((uint)(6));
            w3.BottomAttach = ((uint)(7));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(0));
            w3.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table1.Gtk.Table+TableChild
            this.identry = new Gtk.Entry();
            this.identry.Sensitive = false;
            this.identry.CanFocus = true;
            this.identry.Name = "identry";
            this.identry.IsEditable = true;
            this.identry.InvisibleChar = '●';
            this.table1.Add(this.identry);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.identry]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(3));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("ID : ");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Name : ");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 1F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Category : ");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 1F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Tax : ");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w8.TopAttach = ((uint)(3));
            w8.BottomAttach = ((uint)(4));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 1F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Price : ");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w9.TopAttach = ((uint)(4));
            w9.BottomAttach = ((uint)(5));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 1F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Price + tax : ");
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w10.TopAttach = ((uint)(5));
            w10.BottomAttach = ((uint)(6));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 1F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Icon : ");
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w11.TopAttach = ((uint)(6));
            w11.BottomAttach = ((uint)(7));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.nameentry = new Gtk.Entry();
            this.nameentry.CanFocus = true;
            this.nameentry.Name = "nameentry";
            this.nameentry.IsEditable = true;
            this.nameentry.InvisibleChar = '●';
            this.table1.Add(this.nameentry);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.nameentry]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(3));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.pricespinbutton = new Gtk.SpinButton(0, 100, 1);
            this.pricespinbutton.CanFocus = true;
            this.pricespinbutton.Name = "pricespinbutton";
            this.pricespinbutton.Adjustment.PageIncrement = 10;
            this.pricespinbutton.ClimbRate = 1;
            this.pricespinbutton.Digits = ((uint)(2));
            this.pricespinbutton.Numeric = true;
            this.table1.Add(this.pricespinbutton);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.pricespinbutton]));
            w13.TopAttach = ((uint)(4));
            w13.BottomAttach = ((uint)(5));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(3));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.pricetispinbutton = new Gtk.SpinButton(0, 100, 1);
            this.pricetispinbutton.CanFocus = true;
            this.pricetispinbutton.Name = "pricetispinbutton";
            this.pricetispinbutton.Adjustment.PageIncrement = 10;
            this.pricetispinbutton.ClimbRate = 1;
            this.pricetispinbutton.Digits = ((uint)(2));
            this.pricetispinbutton.Numeric = true;
            this.table1.Add(this.pricetispinbutton);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.pricetispinbutton]));
            w14.TopAttach = ((uint)(5));
            w14.BottomAttach = ((uint)(6));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(3));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.taxcombobox = new Gtk.ComboBox();
            this.taxcombobox.Name = "taxcombobox";
            this.table1.Add(this.taxcombobox);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.taxcombobox]));
            w15.TopAttach = ((uint)(3));
            w15.BottomAttach = ((uint)(4));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(3));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Internal child suposadmin.ProductDialog.ActionArea
            Gtk.HButtonBox w17 = this.ActionArea;
            w17.Name = "dialog1_ActionArea";
            w17.Spacing = 6;
            w17.BorderWidth = ((uint)(5));
            w17.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonCancel]));
            w18.Expand = false;
            w18.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w19 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonOk]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 260;
            this.DefaultHeight = 342;
            this.Show();
            this.taxcombobox.Changed += new System.EventHandler(this.OnTaxChanged);
            this.pricetispinbutton.ValueChanged += new System.EventHandler(this.OnPricetiChanged);
            this.pricespinbutton.ValueChanged += new System.EventHandler(this.OnPriceChanged);
            this.iconbutton.Clicked += new System.EventHandler(this.OnIconClicked);
            this.buttonOk.Clicked += new System.EventHandler(this.OnOk);
        }
    }
}
