// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace suposadmin {
    
    
    public partial class SettingsDialog {
        
        private Gtk.Notebook notebook62;
        
        private Gtk.Table table1;
        
        private Gtk.Entry dbentry;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Entry loginentry;
        
        private Gtk.Entry passentry;
        
        private Gtk.SpinButton portspinbutton;
        
        private Gtk.CheckButton savepasscheckbutton;
        
        private Gtk.Entry serverentry;
        
        private Gtk.Label label63;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget suposadmin.SettingsDialog
            this.Name = "suposadmin.SettingsDialog";
            this.Title = Mono.Unix.Catalog.GetString("Preferences");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child suposadmin.SettingsDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.notebook62 = new Gtk.Notebook();
            this.notebook62.CanFocus = true;
            this.notebook62.Name = "notebook62";
            this.notebook62.CurrentPage = 0;
            // Container child notebook62.Gtk.Notebook+NotebookChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(12));
            // Container child table1.Gtk.Table+TableChild
            this.dbentry = new Gtk.Entry();
            this.dbentry.CanFocus = true;
            this.dbentry.Name = "dbentry";
            this.dbentry.IsEditable = true;
            this.dbentry.InvisibleChar = '●';
            this.table1.Add(this.dbentry);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.dbentry]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 1F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Password :");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w3.TopAttach = ((uint)(5));
            w3.BottomAttach = ((uint)(6));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Server address :");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Port :");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 1F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Database :");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 1F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Login :");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.loginentry = new Gtk.Entry();
            this.loginentry.CanFocus = true;
            this.loginentry.Name = "loginentry";
            this.loginentry.IsEditable = true;
            this.loginentry.InvisibleChar = '●';
            this.table1.Add(this.loginentry);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.loginentry]));
            w8.TopAttach = ((uint)(3));
            w8.BottomAttach = ((uint)(4));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.passentry = new Gtk.Entry();
            this.passentry.CanFocus = true;
            this.passentry.Name = "passentry";
            this.passentry.IsEditable = true;
            this.passentry.Visibility = false;
            this.passentry.InvisibleChar = '●';
            this.table1.Add(this.passentry);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.passentry]));
            w9.TopAttach = ((uint)(5));
            w9.BottomAttach = ((uint)(6));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.portspinbutton = new Gtk.SpinButton(0, 65536, 1);
            this.portspinbutton.CanFocus = true;
            this.portspinbutton.Name = "portspinbutton";
            this.portspinbutton.Adjustment.PageIncrement = 10;
            this.portspinbutton.ClimbRate = 1;
            this.portspinbutton.Numeric = true;
            this.table1.Add(this.portspinbutton);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.portspinbutton]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.savepasscheckbutton = new Gtk.CheckButton();
            this.savepasscheckbutton.CanFocus = true;
            this.savepasscheckbutton.Name = "savepasscheckbutton";
            this.savepasscheckbutton.Label = Mono.Unix.Catalog.GetString("Save password");
            this.savepasscheckbutton.Active = true;
            this.savepasscheckbutton.DrawIndicator = true;
            this.savepasscheckbutton.UseUnderline = true;
            this.table1.Add(this.savepasscheckbutton);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.savepasscheckbutton]));
            w11.TopAttach = ((uint)(4));
            w11.BottomAttach = ((uint)(5));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.serverentry = new Gtk.Entry();
            this.serverentry.CanFocus = true;
            this.serverentry.Name = "serverentry";
            this.serverentry.IsEditable = true;
            this.serverentry.InvisibleChar = '●';
            this.table1.Add(this.serverentry);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.serverentry]));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            this.notebook62.Add(this.table1);
            // Notebook tab
            this.label63 = new Gtk.Label();
            this.label63.Name = "label63";
            this.label63.LabelProp = Mono.Unix.Catalog.GetString("Connexion");
            this.notebook62.SetTabLabel(this.table1, this.label63);
            this.label63.ShowAll();
            w1.Add(this.notebook62);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(w1[this.notebook62]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Internal child suposadmin.SettingsDialog.ActionArea
            Gtk.HButtonBox w15 = this.ActionArea;
            w15.Name = "dialog1_ActionArea";
            w15.Spacing = 6;
            w15.BorderWidth = ((uint)(5));
            w15.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w16 = ((Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonCancel]));
            w16.Expand = false;
            w16.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w17 = ((Gtk.ButtonBox.ButtonBoxChild)(w15[this.buttonOk]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 311;
            this.DefaultHeight = 318;
            this.Show();
            this.buttonOk.Clicked += new System.EventHandler(this.OnOk);
        }
    }
}
