// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace suposadmin {
    
    
    public partial class GeneralInfoViewWidget {
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.Table table1;
        
        private Gtk.Button applybutton;
        
        private Gtk.Entry faxentry;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView addresstextview;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Entry nameentry;
        
        private Gtk.Entry phoneentry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget suposadmin.GeneralInfoViewWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "suposadmin.GeneralInfoViewWidget";
            // Container child suposadmin.GeneralInfoViewWidget.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(9));
            // Container child table1.Gtk.Table+TableChild
            this.applybutton = new Gtk.Button();
            this.applybutton.CanFocus = true;
            this.applybutton.Name = "applybutton";
            this.applybutton.UseStock = true;
            this.applybutton.UseUnderline = true;
            this.applybutton.Label = "gtk-apply";
            this.table1.Add(this.applybutton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.applybutton]));
            w2.TopAttach = ((uint)(4));
            w2.BottomAttach = ((uint)(5));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.faxentry = new Gtk.Entry();
            this.faxentry.CanFocus = true;
            this.faxentry.Name = "faxentry";
            this.faxentry.IsEditable = true;
            this.faxentry.InvisibleChar = '●';
            this.table1.Add(this.faxentry);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.faxentry]));
            w3.TopAttach = ((uint)(3));
            w3.BottomAttach = ((uint)(4));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.addresstextview = new Gtk.TextView();
            this.addresstextview.CanFocus = true;
            this.addresstextview.Name = "addresstextview";
            this.GtkScrolledWindow.Add(this.addresstextview);
            this.table1.Add(this.GtkScrolledWindow);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 1F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Fax number :");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w6.TopAttach = ((uint)(3));
            w6.BottomAttach = ((uint)(4));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Business name :");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.Yalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Address :");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 1F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Phone number :");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.nameentry = new Gtk.Entry();
            this.nameentry.CanFocus = true;
            this.nameentry.Name = "nameentry";
            this.nameentry.IsEditable = true;
            this.nameentry.InvisibleChar = '●';
            this.table1.Add(this.nameentry);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.nameentry]));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.phoneentry = new Gtk.Entry();
            this.phoneentry.CanFocus = true;
            this.phoneentry.Name = "phoneentry";
            this.phoneentry.IsEditable = true;
            this.phoneentry.InvisibleChar = '●';
            this.table1.Add(this.phoneentry);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.phoneentry]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            this.scrolledwindow1.Add(w1);
            this.Add(this.scrolledwindow1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.applybutton.Clicked += new System.EventHandler(this.OnApply);
        }
    }
}
